// src/hunt/core.ts
//
// HuntCore is the heart of the menace loop. One core, many frontends.
// It owns the HuntState, emits HuntEvents to subscribers, and runs
// the continuous observation+attack loop until one of three
// termination conditions is met.

import { EventEmitter } from 'node:events';
import { mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { randomUUID } from 'node:crypto';
import type { HuntEvent, PrimitiveCall, LLMToken, ChatMessageEvent, OOBCallbackEvent, ScreenshotEvent, BudgetUpdate, LogEvent } from './events';
import type { BehavioralStep } from './recorder/step-types';
import type { HuntState, HuntSummary, TerminationReason } from './types';
import type { AppModelFinding } from '../core/app-model';
import type { LLMClient } from '../llm/client';
import { BehavioralRecorder, type BehavioralRecorderOptions } from './recorder/behavioral-recorder';
import { BehavioralAnalyzer } from './observation/analyzer';
import { LiveTestWriter } from '../codegen/live-writer';
import { readJsonl } from './recorder/jsonl-writer';

export interface HuntCoreOptions {
  target: string;
  outDir: string;
  llm: LLMClient;
  /** Wall-clock budget in seconds. Default 0 (unlimited). */
  maxRuntimeSeconds?: number;
  /** Dollar budget. Default 5.0. */
  maxDollars?: number;
  /** Session ID for the recorder. */
  sessionId?: string;
  /** Per-step log to JSONL. Default true. */
  writeJsonl?: boolean;
  /** Always-valid Playwright spec on disk. Default true. */
  writeLiveSpec?: boolean;
}

export class HuntCore {
  private opts: Required<Omit<HuntCoreOptions, 'llm' | 'sessionId'>> & { sessionId: string };
  private llm: LLMClient;
  private emitter = new EventEmitter();
  private state: HuntState;
  private recorder: BehavioralRecorder | null = null;
  private analyzer: BehavioralAnalyzer;
  private liveSpec: LiveTestWriter | null = null;
  private startTime = Date.now();
  private timerHandle: NodeJS.Timeout | null = null;
  private started = false;
  private stopped = false;

  constructor(opts: HuntCoreOptions) {
    this.opts = {
      target: opts.target,
      outDir: opts.outDir,
      maxRuntimeSeconds: opts.maxRuntimeSeconds ?? 0, // 0 = unlimited (Block 9c.2)
      maxDollars: opts.maxDollars ?? 5.0,
      writeJsonl: opts.writeJsonl ?? true,
      writeLiveSpec: opts.writeLiveSpec ?? true,
      sessionId: opts.sessionId ?? randomUUID(),
    };
    this.llm = opts.llm;
    if (!existsSync(this.opts.outDir)) mkdirSync(this.opts.outDir, { recursive: true });
    this.state = {
      target: this.opts.target,
      startedAt: Date.now(),
      endedAt: null,
      terminationReason: null,
      maxRuntimeSeconds: this.opts.maxRuntimeSeconds,
      maxDollars: this.opts.maxDollars,
      dollarsSpent: 0,
      phase: 'starting',
      activeAgentIds: new Set(),
      findings: [],
      behavioralStepCount: 0,
      primitiveCallCount: 0,
      oobCallbackCount: 0,
      screenshotCount: 0,
    };
    this.analyzer = new BehavioralAnalyzer();
    this.emitter.setMaxListeners(50);
  }

  // -- subscriptions --

  on(listener: (event: HuntEvent) => void): () => void {
    this.emitter.on('event', listener);
    return () => this.emitter.off('event', listener);
  }

  emit(event: HuntEvent): void {
    this.emitter.emit('event', event);
  }

  // -- accessors --

  getState(): HuntState {
    return this.state;
  }

  getAnalyzer(): BehavioralAnalyzer {
    return this.analyzer;
  }

  getRecorder(): BehavioralRecorder | null {
    return this.recorder;
  }

  getLiveSpec(): LiveTestWriter | null {
    return this.liveSpec;
  }

  // -- lifecycle --

  start(): void {
    if (this.started) throw new Error('HuntCore already started');
    this.started = true;
    this.startTime = Date.now();
    this.state.startedAt = this.startTime;
    this.state.phase = 'observing';

    if (this.opts.writeJsonl) {
      const jsonlPath = join(this.opts.outDir, 'behavioral.jsonl');
      this.recorder = new BehavioralRecorder({
        jsonlPath,
        sessionId: this.opts.sessionId,
        tabId: 'main',
      } satisfies BehavioralRecorderOptions);
      this.recorder.onStep((step) => {
        this.state.behavioralStepCount += 1;
        this.analyzer.ingest(step);
        this.emit({ type: 'behavioral-step', step });
      });
    }

    if (this.opts.writeLiveSpec) {
      const livePath = join(this.opts.outDir, 'live.spec.ts');
      this.liveSpec = new LiveTestWriter({
        outPath: livePath,
        baseUrl: this.opts.target,
        testName: `Hunt ${this.opts.target}`,
        description: `Auto-generated by Ultimatrix on ${new Date().toISOString()}`,
      });
    }

    this.emit({ type: 'phase', phase: 'starting' });
    this.emit({ type: 'phase', phase: 'observing' });

    this.timerHandle = setInterval(() => this.tick(), 1000);
    this.tick();
  }

  stop(reason: TerminationReason): HuntSummary {
    if (this.stopped) {
      return this.buildSummary(this.state.terminationReason ?? reason);
    }
    this.stopped = true;
    this.state.endedAt = Date.now();
    this.state.terminationReason = reason;
    this.state.phase = 'done';
    if (this.timerHandle) {
      clearInterval(this.timerHandle);
      this.timerHandle = null;
    }
    if (this.recorder) {
      this.recorder.detach();
    }
    if (this.liveSpec) {
      this.liveSpec.finalise();
    }
    this.analyzer.finaliseCurrentFlow('hunt ended');
    const summary = this.buildSummary(reason);
    this.emit({ type: 'done', reason, summary });
    return summary;
  }

  async stopAsync(reason: TerminationReason): Promise<HuntSummary> {
    return this.stop(reason);
  }

  // -- event sink (other modules push events in) --

  recordPrimitiveCall(call: PrimitiveCall): void {
    this.state.primitiveCallCount += 1;
    this.emit({ type: 'primitive-call', call });
    if (this.liveSpec) this.liveSpec.appendPrimitiveCall(call);
  }

  recordLLMToken(token: LLMToken): void {
    this.emit({ type: 'llm-token', token });
  }

  recordChatMessage(message: ChatMessageEvent): void {
    this.emit({ type: 'chat-message', message });
  }

  recordOOB(callback: OOBCallbackEvent): void {
    this.state.oobCallbackCount += 1;
    this.emit({ type: 'oob-callback', callback });
  }

  recordScreenshot(screenshot: ScreenshotEvent): void {
    this.state.screenshotCount += 1;
    this.emit({ type: 'screenshot', screenshot });
  }

  recordFinding(finding: AppModelFinding): boolean {
    // Dedup: same (type, endpoint, param) replaces existing.
    const existing = this.state.findings.find(
      (f) => f.type === finding.type && f.endpoint === finding.endpoint && f.param === finding.param
    );
    if (existing) {
      this.emit({ type: 'finding-deduped', finding, existingId: existing.id ?? 'unknown' });
      return false;
    }
    if (!finding.id) finding.id = randomUUID();
    this.state.findings.push(finding);
    this.emit({ type: 'finding', finding });
    if (this.liveSpec) this.liveSpec.appendFinding(finding);
    return true;
  }

  recordLog(log: LogEvent): void {
    this.emit({ type: 'log', log });
  }

  // -- internals --

  private tick(): void {
    if (this.stopped) return;
    const elapsedSeconds = (Date.now() - this.startTime) / 1000;
    // Block 9c.2: maxRuntimeSeconds === 0 means "unlimited", skip the
    // time-budget check entirely. Same for the remaining/eta computation
    // — when unlimited, we report Infinity so the UI shows no countdown.
    if (this.state.maxRuntimeSeconds > 0 && elapsedSeconds >= this.state.maxRuntimeSeconds) {
      this.stop('time-budget');
      return;
    }
    if (this.state.dollarsSpent >= this.state.maxDollars) {
      this.stop('budget-spent');
      return;
    }
    const isUnlimited = this.state.maxRuntimeSeconds === 0;
    const budget: BudgetUpdate = {
      spent: this.state.dollarsSpent,
      limit: this.state.maxDollars,
      remainingSeconds: isUnlimited ? Infinity : Math.max(0, this.state.maxRuntimeSeconds - elapsedSeconds),
      etaSeconds: isUnlimited ? Infinity : Math.max(0, this.state.maxRuntimeSeconds - elapsedSeconds),
    };
    this.emit({ type: 'budget-update', budget });
  }

  private buildSummary(reason: TerminationReason): HuntSummary {
    const findingsBySeverity: Record<string, number> = {};
    const findingsByType: Record<string, number> = {};
    for (const f of this.state.findings) {
      const sev = f.severity || 'unknown';
      findingsBySeverity[sev] = (findingsBySeverity[sev] ?? 0) + 1;
      const t = f.type || 'unknown';
      findingsByType[t] = (findingsByType[t] ?? 0) + 1;
    }
    return {
      durationMs: (this.state.endedAt ?? Date.now()) - this.state.startedAt,
      totalSteps: this.state.behavioralStepCount,
      totalPrimitiveCalls: this.state.primitiveCallCount,
      findingsCount: this.state.findings.length,
      findingsBySeverity,
      findingsByType,
      oobCallbacks: this.state.oobCallbackCount,
      screenshots: this.state.screenshotCount,
      cost: this.state.dollarsSpent,
    };
  }
}

/** Replay a previous hunt's behavioral JSONL into a fresh analyzer. */
export async function replayHunt(jsonlPath: string): Promise<BehavioralAnalyzer> {
  const analyzer = new BehavioralAnalyzer();
  for await (const step of readJsonl<BehavioralStep>(jsonlPath)) {
    analyzer.ingest(step);
  }
  return analyzer;
}
