// Generated by Ultimatrix — regression test for 39615c25-e612-4b25-a163-d747aed7b8f9
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding 39615c25-e612-4b25-a163-d747aed7b8f9 — idor-v3 @ http://127.0.0.1:4567/api/users/2', () => {
  const finding = findingsById.get("39615c25-e612-4b25-a163-d747aed7b8f9") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/2");
    expect(res.status()).toBeLessThan(500);
  });
});
