// Generated by Ultimatrix — regression test for cc51045e-49e3-48e2-b90c-5a4372a7ac56
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding cc51045e-49e3-48e2-b90c-5a4372a7ac56 — idor-v3 @ http://127.0.0.1:4567/api/users/3', () => {
  const finding = findingsById.get("cc51045e-49e3-48e2-b90c-5a4372a7ac56") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/3");
    expect(res.status()).toBeLessThan(500);
  });
});
