// Generated by Ultimatrix — regression test for c95723bf-8de7-43b3-aa14-8e97f6c16209
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding c95723bf-8de7-43b3-aa14-8e97f6c16209 — idor-v3 @ http://127.0.0.1:4567/api/users/3', () => {
  const finding = findingsById.get("c95723bf-8de7-43b3-aa14-8e97f6c16209") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/3");
    expect(res.status()).toBeLessThan(500);
  });
});
