// Generated by Ultimatrix — regression test for bc226b54-0eb2-40dd-beee-450395c4b23e
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding bc226b54-0eb2-40dd-beee-450395c4b23e — idor-v3 @ http://127.0.0.1:4567/api/users/3', () => {
  const finding = findingsById.get("bc226b54-0eb2-40dd-beee-450395c4b23e") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/3");
    expect(res.status()).toBeLessThan(500);
  });
});
