// Generated by Ultimatrix — regression test for b25887b1-2b18-4985-91c7-742ca6d7ed07
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding b25887b1-2b18-4985-91c7-742ca6d7ed07 — idor-v3 @ http://127.0.0.1:4567/api/users/1', () => {
  const finding = findingsById.get("b25887b1-2b18-4985-91c7-742ca6d7ed07") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/1");
    expect(res.status()).toBeLessThan(500);
  });
});
