// Generated by Ultimatrix — regression test for e88f8d33-eae3-46af-8c1b-aee43417d80f
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding e88f8d33-eae3-46af-8c1b-aee43417d80f — idor-v3 @ http://127.0.0.1:4567/api/users/2', () => {
  const finding = findingsById.get("e88f8d33-eae3-46af-8c1b-aee43417d80f") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/2");
    expect(res.status()).toBeLessThan(500);
  });
});
