// Generated by Ultimatrix — regression test for c646b91d-1092-4628-b9b2-49888b3773af
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding c646b91d-1092-4628-b9b2-49888b3773af — idor-v3 @ http://127.0.0.1:4567/api/users/3', () => {
  const finding = findingsById.get("c646b91d-1092-4628-b9b2-49888b3773af") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/3");
    expect(res.status()).toBeLessThan(500);
  });
});
