// Generated by Ultimatrix — regression test for 8b2ad075-28f5-4b2d-89fd-e74e5668f985
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding 8b2ad075-28f5-4b2d-89fd-e74e5668f985 — idor-v3 @ http://127.0.0.1:4567/api/users/1', () => {
  const finding = findingsById.get("8b2ad075-28f5-4b2d-89fd-e74e5668f985") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/1");
    expect(res.status()).toBeLessThan(500);
  });
});
