// Generated by Ultimatrix — regression test for 4d082061-9515-4bf9-9509-6032c7232881
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding 4d082061-9515-4bf9-9509-6032c7232881 — idor-v3 @ http://127.0.0.1:4567/api/users/1', () => {
  const finding = findingsById.get("4d082061-9515-4bf9-9509-6032c7232881") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/1");
    expect(res.status()).toBeLessThan(500);
  });
});
