// Generated by Ultimatrix — regression test for 291963bc-3c00-4248-958f-a607281f35d8
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding 291963bc-3c00-4248-958f-a607281f35d8 — idor-v3 @ http://127.0.0.1:4567/api/users/2', () => {
  const finding = findingsById.get("291963bc-3c00-4248-958f-a607281f35d8") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/2");
    expect(res.status()).toBeLessThan(500);
  });
});
