// Generated by Ultimatrix — regression test for a9caee4d-0cc4-4654-ba28-8f14483ac428
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding a9caee4d-0cc4-4654-ba28-8f14483ac428 — idor-v3 @ http://127.0.0.1:4567/api/users/2', () => {
  const finding = findingsById.get("a9caee4d-0cc4-4654-ba28-8f14483ac428") || findings[0];

  test('reproduces idor-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/2");
    expect(res.status()).toBeLessThan(500);
  });
});
