// Generated by Ultimatrix — regression test for f-2
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding f-2 — sqli @ /api/users', () => {
  const finding = findingsById.get("f-2") || findings[0];

  test('reproduces sqli', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    await request.post("/api/users", { data: { "id": "' OR 1=1--" } });
    expect(res.status()).toBeLessThan(500);
  });
});
