// Generated by Ultimatrix — regression test for f-1
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding f-1 — xss @ /search', () => {
  const finding = findingsById.get("f-1") || findings[0];

  test('reproduces xss', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const url = "/search".split('?')[0] + '?' + "q" + '=' + encodeURIComponent("<script>");
    const res = await request.get(url);
    expect(res.status()).toBeLessThan(500);
  });
});
