// Generated by Ultimatrix — regression test for synth-headers-1
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding synth-headers-1 — headers @ http://127.0.0.1:4567/', () => {
  const finding = findingsById.get("synth-headers-1") || findings[0];

  test('reproduces headers', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/");
    expect(res.status()).toBeLessThan(500);
  });
});
