// Generated by Ultimatrix — regression test for synth-xss-1
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding synth-xss-1 — xss @ http://127.0.0.1:4567/api/preview', () => {
  const finding = findingsById.get("synth-xss-1") || findings[0];

  test('reproduces xss', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/preview");
    expect(res.status()).toBeLessThan(500);
  });
});
