// Generated by Ultimatrix — regression test for synth-idor-1
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding synth-idor-1 — idor @ http://127.0.0.1:4567/api/users/1', () => {
  const finding = findingsById.get("synth-idor-1") || findings[0];

  test('reproduces idor', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users/1");
    expect(res.status()).toBeLessThan(500);
  });
});
