// Generated by Ultimatrix — regression test for synth-sqli-1
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding synth-sqli-1 — sqli @ http://127.0.0.1:4567/api/users', () => {
  const finding = findingsById.get("synth-sqli-1") || findings[0];

  test('reproduces sqli', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("http://127.0.0.1:4567/api/users");
    expect(res.status()).toBeLessThan(500);
  });
});
