import { writeFile, readFile, readdir, mkdir, unlink } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { resolve, join } from 'node:path'
import type { TestCase } from './test-generator'

export interface StoredTest {
  id: string
  name: string
  code: string
  findingId: string
  generatedAt: string
  filePath: string
}

export class TestStorage {
  private baseDir: string

  constructor(baseDir: string) {
    this.baseDir = baseDir
  }

  async save(tests: TestCase[]): Promise<void> {
    const dir = resolve(this.baseDir, 'tests')
    try {
      await mkdir(dir, { recursive: true })
    } catch (error: unknown) {
      if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error
    }

    for (const test of tests) {
      const filePath = join(dir, `${test.id}.spec.ts`)
      const content = this.wrapWithMetadata(test)
      await writeFile(filePath, content, 'utf-8')
    }

    const index = tests.map(t => ({
      id: t.id,
      name: t.name,
      findingId: t.findingId,
      severity: t.severity,
      category: t.category,
    }))
    await writeFile(join(dir, 'index.json'), JSON.stringify(index, null, 2), 'utf-8')
  }

  async load(dir?: string): Promise<StoredTest[]> {
    const testDir = dir || resolve(this.baseDir, 'tests')

    let files: string[]
    try {
      files = await readdir(testDir)
    } catch {
      return []
    }

    const specFiles = files.filter(f => f.endsWith('.spec.ts'))
    const tests: StoredTest[] = []

    for (const file of specFiles) {
      try {
        const content = await readFile(join(testDir, file), 'utf-8')
        const meta = this.extractMetadata(content)
        tests.push({
          id: file.replace('.spec.ts', ''),
          name: meta.name || file,
          code: content,
          findingId: meta.findingId || '',
          generatedAt: meta.generatedAt || '',
          filePath: join(testDir, file),
        })
      } catch {
        // Skip unreadable files
      }
    }

    return tests
  }

  async list(dir?: string): Promise<string[]> {
    const testDir = dir || resolve(this.baseDir, 'tests')

    let files: string[]
    try {
      files = await readdir(testDir)
    } catch {
      return []
    }

    return files.filter(f => f.endsWith('.spec.ts'))
  }

  async remove(testId: string): Promise<void> {
    const filePath = resolve(this.baseDir, 'tests', `${testId}.spec.ts`)
    if (existsSync(filePath)) {
      await unlink(filePath)
    }
  }

  async exists(testId: string): Promise<boolean> {
    const filePath = resolve(this.baseDir, 'tests', `${testId}.spec.ts`)
    return existsSync(filePath)
  }

  private wrapWithMetadata(test: TestCase): string {
    const header = [
      `/**`,
      ` * Test: ${test.name}`,
      ` * Finding ID: ${test.findingId}`,
      ` * Severity: ${test.severity}`,
      ` * Category: ${test.category}`,
      ` * Generated: ${new Date().toISOString()}`,
      ` * Generated by: ultimatrix`,
      ` */`,
      '',
    ].join('\n')

    return header + test.code
  }

  private extractMetadata(content: string): Record<string, string> {
    const meta: Record<string, string> = {}
    const lines = content.split('\n')

    for (const line of lines) {
      if (!line.startsWith(' * ')) continue

      const match = line.match(/^ \* (.+?): (.+)$/)
      if (match) {
        const [, key, value] = match
        meta[key.toLowerCase().replace(/\s+/g, '')] = value.trim()
      }
    }

    return meta
  }
}
