// Generated by Ultimatrix — do not edit by hand
import type { AppModelFinding } from '../../src/core/app-model';

export interface FindingFixture {
  id: string;
  type: string;
  severity: string;
  endpoint: string;
  method: string;
  param: string;
  payload: string;
  confidence: number;
  description: string;
}

export const findings: FindingFixture[] = [
  {
    id: "caed9628-56cd-4f48-adb1-f04fb62835d1",
    type: "idor-v3",
    severity: "high",
    endpoint: "http://127.0.0.1:4567/api/users/1",
    method: "GET",
    param: "",
    payload: "",
    confidence: "high",
    description: "",
  },
  {
    id: "2165ea4b-5cc3-41e1-8262-4881342c3169",
    type: "idor-v3",
    severity: "high",
    endpoint: "http://127.0.0.1:4567/api/users/2",
    method: "GET",
    param: "",
    payload: "",
    confidence: "high",
    description: "",
  },
  {
    id: "1bd795ef-e5dc-4cd6-b934-f39f177b0339",
    type: "idor-v3",
    severity: "high",
    endpoint: "http://127.0.0.1:4567/api/users/3",
    method: "GET",
    param: "",
    payload: "",
    confidence: "high",
    description: "",
  }
];

export const findingsById = new Map(findings.map((f) => [f.id, f]));
export const findingsBySeverity = (s: string) => findings.filter((f) => f.severity === s);
export const findingsByType = (t: string) => findings.filter((f) => f.type === t);
