// Generated by Ultimatrix — do not edit by hand
import { Page, request as playwrightRequest } from '@playwright/test';

export interface AuthCreds {
  username: string;
  password: string;
  email?: string;
}

export const auth: AuthCreds | null = {
  "username": "admin",
  "password": "secret"
};

export async function loginAs(page: Page, creds: AuthCreds = auth!): Promise<void> {
  if (!creds) throw new Error('No auth credentials configured');
  await page.goto('/login');
  await page.fill('input[name="email"], input[name="username"]', creds.email || creds.username);
  await page.fill('input[name="password"]', creds.password);
  await page.click('button[type="submit"]');
  await page.waitForLoadState('load');
}
