// Generated by Ultimatrix — do not edit by hand
import type { AppModelFinding } from '../../src/core/app-model';

export interface FindingFixture {
  id: string;
  type: string;
  severity: string;
  endpoint: string;
  method: string;
  param: string;
  payload: string;
  confidence: number;
  description: string;
}

export const findings: FindingFixture[] = [
  {
    id: "f-1",
    type: "xss",
    severity: "high",
    endpoint: "/search",
    method: "GET",
    param: "q",
    payload: "<script>",
    confidence: "high",
    description: "",
  },
  {
    id: "f-2",
    type: "sqli",
    severity: "critical",
    endpoint: "/api/users",
    method: "POST",
    param: "id",
    payload: "' OR 1=1--",
    confidence: "medium",
    description: "",
  }
];

export const findingsById = new Map(findings.map((f) => [f.id, f]));
export const findingsBySeverity = (s: string) => findings.filter((f) => f.severity === s);
export const findingsByType = (t: string) => findings.filter((f) => f.type === t);
