// src/codegen/finalize.ts
//
// codegen — finalise the live spec on disk into a runnable Playwright
// test. Adds imports, wraps the body in a test() block (it's already
// wrapped by the live writer; this is a no-op currently), and writes
// a sibling README with usage instructions.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, basename, join } from 'node:path';

export interface FinalizeOptions {
  liveSpecPath: string;
  /** Output dir for the finalised test (defaults to same dir as liveSpec). */
  outDir?: string;
  /** Test name override. */
  testName?: string;
}

/** Read the live spec, decorate it as a real Playwright test, and write to outDir. */
export function finalizeLiveSpec(opts: FinalizeOptions): string {
  if (!existsSync(opts.liveSpecPath)) {
    throw new Error(`Live spec not found: ${opts.liveSpecPath}`);
  }
  const content = readFileSync(opts.liveSpecPath, 'utf8');
  const outDir = opts.outDir ?? dirname(opts.liveSpecPath);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, `${basename(opts.liveSpecPath, '.spec.ts')}.finalised.spec.ts`);
  // The live spec is already a valid Playwright test (the live writer keeps it valid).
  // We just re-emit it with a small banner.
  const banner = `// FINALISED by ultimatrix codegen. Run: npx playwright test ${basename(outPath)}\n`;
  writeFileSync(outPath, banner + content);
  // Write a README.
  const readmePath = join(outDir, 'README.md');
  const readme = `# Generated test

This test was auto-generated by Ultimatrix. It captures the exact
actions the agent took during the hunt — every navigation, click,
fill, and request — plus \`expect()\` assertions for every finding.

## Run

\`\`\`
npx playwright install  # first time only
npx playwright test ${basename(outPath)}
\`\`\`

## Why?

When a finding is emitted, an \`expect()\` assertion is added to the
test. If the finding is real, the test will pass. If the finding is a
false positive or the underlying bug gets fixed, the test will fail,
giving you regression coverage for free.
`;
  writeFileSync(readmePath, readme);
  return outPath;
}
