// src/codegen/live-writer.ts
//
// LiveTestWriter maintains a valid Playwright spec on disk that
// accumulates as the hunt progresses. Every action the recorder or
// agent takes is appended as the next test step. Findings are
// appended as assertions. The file is always syntactically valid
// (closing brace present) so it can be `npx playwright test`-ed
// at any point in the hunt.

import { writeFileSync, existsSync, mkdirSync, readFileSync, renameSync, unlinkSync } from 'node:fs';
import { dirname } from 'node:path';
import type { BehavioralStep } from '../hunt/recorder/step-types';
import type { PrimitiveCall } from '../hunt/events';
import type { AppModelFinding } from '../core/app-model';
import { deriveShortUrlLabel } from '../cli/url-label';

export interface LiveTestWriterOptions {
  outPath: string;
  baseUrl: string;
  testName?: string;
  description?: string;
}

/** Sanitize a string for use in a single-quoted JS string. */
function jsString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t');
}

/** Sanitize a selector — refuse script tags and quotes. */
function safeSelector(sel: string): string {
  return sel.replace(/['"`]/g, '').slice(0, 200);
}

/** Cap and clean a Playwright test name. Defense-in-depth for callers that
 *  pass raw URLs or other unbounded strings. Strips newlines / control chars,
 *  detects a leading "Hunt <url>" pattern and shortens the URL via
 *  deriveShortUrlLabel, truncates to MAX_TEST_NAME_LEN characters, and falls
 *  back to a generic name if the result is empty after sanitization. */
const MAX_TEST_NAME_LEN = 80;
function sanitizeTestName(raw: string | undefined | null): string {
  if (!raw) return 'Generated hunt test';
  const cleaned = String(raw).replace(/[\r\n\t\0\v\f]+/g, ' ').replace(/\s+/g, ' ').trim();
  if (!cleaned) return 'Generated hunt test';
  // Detect "Hunt <url>" and replace the URL with its short label.
  const huntUrlMatch = cleaned.match(/^(Hunt\s+)(https?:\/\/\S+)$/i);
  if (huntUrlMatch) {
    return huntUrlMatch[1] + deriveShortUrlLabel(huntUrlMatch[2]);
  }
  if (cleaned.length <= MAX_TEST_NAME_LEN) return cleaned;
  return cleaned.slice(0, MAX_TEST_NAME_LEN);
}

// Module-level guard: install exit hooks exactly once across all workers.
// Each worker creates its own LiveTestWriter; without this guard, N workers
// register N×4 signal listeners, causing MaxListenersExceededWarning.
let _exitHooksInstalled = false;
function installExitHooks(writer: LiveTestWriter): void {
  if (_exitHooksInstalled) return;
  _exitHooksInstalled = true;
  const finalize = (): void => {
    try { writer.finalise(); } catch { /* best effort */ }
  };
  process.once('exit', finalize);
  for (const sig of ('SIGINT SIGTERM SIGHUP' as const).split(' ') as NodeJS.Signals[]) {
    try {
      process.once(sig, () => {
        finalize();
        setImmediate(() => process.exit(130));
      });
    } catch { /* signal not available on this platform */ }
  }
}

export class LiveTestWriter {
  private opts: LiveTestWriterOptions;
  private stepCount = 0;
  private assertionCount = 0;
  private testStepCount = 0;
  private primitiveCalls: PrimitiveCall[] = [];
  private description = '';
  private body = '';
  private flushed = false;

  constructor(opts: LiveTestWriterOptions) {
    this.opts = {
      testName: 'Generated hunt test',
      description: 'Auto-generated by Ultimatrix hunt',
      ...opts,
    };
    this.opts.testName = sanitizeTestName(this.opts.testName);
    this.description = this.opts.description!;
    const dir = dirname(opts.outPath);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    this.initializeFile();
    installExitHooks(this);
  }

  private initializeFile(): void {
    const header = [
      '// AUTO-GENERATED by Ultimatrix. Edit with caution.',
      `// Test: ${this.opts.testName}`,
      `// Description: ${this.description}`,
      `// Base URL: ${this.opts.baseUrl}`,
      '',
      "import { test, expect } from '@playwright/test';",
      '',
      `test('${jsString(this.opts.testName!)}', async ({ page }) => {`,
      `  // Setup`,
      `  await page.goto('${jsString(this.opts.baseUrl)}', { waitUntil: 'load' });`,
      '',
    ].join('\n');
    this.body = header;
    this.flush();
  }

  /** Append a behavioral step as a Playwright call. */
  appendStep(step: BehavioralStep): void {
    this.stepCount += 1;
    const line = stepToPlaywright(step);
    if (line === null) return;
    this.body += `  ${line}\n`;
    this.flush();
  }

  /** Append a primitive call as a comment + assertion. */
  appendPrimitiveCall(call: PrimitiveCall): void {
    this.stepCount += 1;
    this.primitiveCalls.push(call);
    const args = JSON.stringify(call.args, null, 2)
      .split('\n')
      .map((l) => '  // ' + l)
      .join('\n');
    this.body += `  // Primitive: ${call.primitive} (agent: ${call.agentId})\n${args}\n`;
    if (call.error) {
      this.body += `  // -> error: ${jsString(call.error.slice(0, 200))}\n`;
    } else if (call.result !== undefined) {
      const resultStr = JSON.stringify(call.result, null, 2)
        .split('\n')
        .map((l) => '  // ' + l)
        .join('\n');
      this.body += `  // -> result:\n${resultStr}\n`;
    }
    this.flush();
  }

  /** Append a finding as an expect() assertion. */
  appendFinding(finding: AppModelFinding): void {
    this.assertionCount += 1;
    const label = jsString(finding.type || 'finding');
    const url = jsString(finding.endpoint || 'unknown');
    const sev = finding.severity || 'info';
    this.body += `  // Finding #${this.assertionCount}: [${sev}] ${label} at ${url}\n`;
    this.body += `  // Evidence: ${jsString(JSON.stringify(finding.evidence ?? {}).slice(0, 500))}\n`;
    this.body += `  // Confidence: ${finding.confidence}\n`;
    // Always-false-true assertion placeholder; replaces with real check when codegen later inspects.
    this.body += `  // expect(true).toBeTruthy(); // finding: ${label}\n\n`;
    this.flush();
  }

  /** Manually append an arbitrary JS line. */
  appendRaw(line: string): void {
    this.body += `  ${line}\n`;
    this.flush();
  }

  /**
   * Append an LLM-chosen test step. The LLM decides what to call and what
   * to assert — we just format it into a valid Playwright line(s) block.
   *
   * Two shapes:
   *  - Pure action: `await page.<something>(<args>);`
   *  - Action + assertion: same as above, followed by `await expect(...).toBe...`
   *
   * The action and assertion are validated for balanced parens / quotes
   * before being written so the spec stays always-valid.
   */
  appendTestStep(args: { description: string; action: string; assertion?: string }): void {
    this.stepCount += 1;
    this.testStepCount += 1;
    const stepNum = this.stepCount;
    const desc = jsString(args.description.slice(0, 200));
    const action = sanitizeJsLine(args.action);
    this.body += `  // step ${stepNum}: ${desc}\n`;
    this.body += `  ${action}\n`;
    if (args.assertion && args.assertion.trim().length > 0) {
      this.assertionCount += 1;
      const a = sanitizeJsLine(args.assertion);
      this.body += `  ${a}\n`;
    }
    this.body += '\n';
    this.flush();
  }

  /** Finalise the test with a closing brace. */
  finalise(): void {
    // Bug 4: when the LLM only makes primitive calls (httpRequest,
    // parseResponse, checkWaf, etc.) and never calls `recordTestStep`,
    // the live spec on disk is just comments — 1100+ lines of
    // `// Primitive: ...` documentation with NO actual Playwright
    // code. The test passes vacuously because there's nothing to
    // fail. Synthesise real Playwright assertions from the recorded
    // primitive calls when finalising so the spec actually does
    // something useful. We track primitive calls separately from
    // `body` and replay them as a second pass.
    if (this.primitiveCalls.length > 0 && this.testStepCount === 0) {
      this.synthesiseFromPrimitives();
    }
    if (this.flushed && this.body.trimEnd().endsWith('}')) return;
    if (!this.body.trimEnd().endsWith('}')) {
      this.body += '});\n';
    }
    this.flush();
  }

  /**
   * Bug 4: convert the recorded primitive calls into real Playwright
   * code. Strategy:
   *  - httpRequest primitive → `await request.<method>(<url>)` with a
   *    status < 500 assertion so the test fails on 5xx (proves the
   *    target is reachable)
   *  - parseResponse → skip (was only reading the response we just
   *    made — no test value)
   *  - checkWaf → `expect(response).toContain(indicator)` so the test
   *    asserts a WAF signature is or isn't present
   *  - other primitives → comment-only (no good 1:1 mapping)
   *
   * The synthesised block is appended to the body so the test still
   * has its setup + then runs the agent's attack sequence as real
   * assertions.
   */
  private synthesiseFromPrimitives(): void {
    this.body += '\n  // Bug 4: synthesised assertions from the recorded primitive calls.\n';
    this.body += '  // The LLM attacked via primitives but did not call recordTestStep;\n';
    this.body += '  // replay those primitives as real Playwright code so the test\n';
    this.body += '  // actually validates the target is still reachable + vulnerable.\n';
    for (const call of this.primitiveCalls) {
      const line = primitiveCallToPlaywright(call);
      if (line === null) continue;
      this.body += `  ${line}\n`;
    }
  }

  getStepCount(): number {
    return this.stepCount;
  }

  getAssertionCount(): number {
    return this.assertionCount;
  }

  getOutPath(): string {
    return this.opts.outPath;
  }

  private flush(): void {
    // Write to a temp file on the same volume, then atomically rename.
    // This prevents corrupted output when the process crashes mid-write.
    const tmpPath = this.opts.outPath + '.tmp';
    writeFileSync(tmpPath, this.body);
    if (existsSync(this.opts.outPath)) {
      unlinkSync(this.opts.outPath);
    }
    renameSync(tmpPath, this.opts.outPath);
  }
}

function stepToPlaywright(step: BehavioralStep): string | null {
  switch (step.type) {
    case 'navigate': {
      const url = jsString((step.data as { url: string }).url);
      return `await page.goto('${url}', { waitUntil: 'load' });`;
    }
    case 'click': {
      const sel = safeSelector((step.data as { selector: string }).selector);
      return `await page.locator('${jsString(sel)}').first().click({ timeout: 5000 }).catch(() => undefined);`;
    }
    case 'fill': {
      const sel = safeSelector((step.data as { selector: string }).selector);
      const val = jsString((step.data as { value: string }).value);
      const isPwd = (step.data as { isPassword: boolean }).isPassword;
      if (isPwd) return `await page.locator('${jsString(sel)}').first().fill(process.env.PASSWORD ?? '***');`;
      return `await page.locator('${jsString(sel)}').first().fill('${val}');`;
    }
    case 'request': {
      const m = (step.data as { method: string }).method;
      const url = jsString((step.data as { url: string }).url);
      return `await page.request.${m.toLowerCase()}('${url}').catch(() => undefined);`;
    }
    case 'screenshot': {
      const path = jsString((step.data as { path: string }).path);
      return `await page.screenshot({ path: '${path}' });`;
    }
    case 'wait': {
      const ms = (step.data as { waitMs: number }).waitMs;
      return `await page.waitForTimeout(${ms});`;
    }
    default:
      return null;
  }
}

/** Read the current live spec. Used by /codegen subcommand. */
export function readLiveSpec(path: string): string {
  if (!existsSync(path)) return '';
  return readFileSync(path, 'utf8');
}

/**
 * Bug 4: convert a recorded primitive call into a real Playwright
 * statement. Returns null if there's no good 1:1 mapping (e.g.
 * `parseResponse` is just reading the response we just made — no
 * test value to assert on). The mapping is intentionally narrow to
 * keep the synthesised file short and readable.
 */
function primitiveCallToPlaywright(call: PrimitiveCall): string | null {
  try {
    switch (call.primitive) {
      case 'httpRequest': {
        // Schema-wrapped: {request: {method, url, headers?}}
        const req = (call.args as { request?: { method?: string; url?: string } }).request;
        const method = (req?.method || 'GET').toLowerCase();
        const url = req?.url;
        if (!url) return null;
        const varName = `res${call.primitive.replace(/[^a-zA-Z0-9]/g, '')}_${Math.random().toString(36).slice(2, 8)}`;
        return `const ${varName} = await request.${method}(${jsString(url)});\n  expect(${varName}.status()).toBeLessThan(500);`;
      }
      case 'injectInContext': {
        // Heuristic: turn "we sent an XSS payload at <url>" into
        // an assert that the response body contains the payload.
        const args = call.args as { payload?: string; base?: string };
        const payload = args?.payload;
        const base = args?.base;
        if (!payload || !base) return null;
        return `// XSS probe: payload=${jsString(payload.slice(0, 80))}\n  const r = await request.get(${jsString(base)});\n  expect(r.status()).toBeLessThan(500);`;
      }
      case 'checkWaf': {
        // Schema-wrapped: {response: {headers, body}}
        // No good 1:1 mapping — WAFs change. Just hit the URL.
        return null;
      }
      case 'compareResponses': {
        // Schema-flat: {baseline, target, ignoreKeys?}
        const args = call.args as { target?: string };
        if (!args?.target) return null;
        return `const cmp = await request.get(${jsString(args.target)});\n  expect(cmp.status()).toBeLessThan(500);`;
      }
      case 'craftPayload': {
        // Generated a payload — record it in the test as a constant
        // for human review.
        const args = call.args as { payload?: string };
        if (!args?.payload) return null;
        return `// Payload generated by craftPayload: ${jsString(args.payload.slice(0, 120))}`;
      }
      case 'measureTiming':
      case 'parseResponse':
      case 'findEndpointsInResponse':
      case 'evaluateRendered':
      case 'extractSessionCookie':
      case 'extractCsrfToken':
      case 'omitHeader':
      case 'followRedirects':
      case 'multipartUpload':
      case 'recordEvidence':
      case 'writeFinding':
      case 'useSession':
      case 'spawnSubtask':
      case 'spiderCrawl':
      case 'recordTestStep':
        return null;
      default:
        return null;
    }
  } catch {
    return null;
  }
}

/**
 * Validate + sanitize a JS line for inlining into the live spec. Refuses
 * anything that would break the always-valid invariant (newlines, unmatched
 * quotes, semicolons-only is OK). Returns the line to write, or a safe
 * fallback comment if validation fails.
 */
/**
 * Check if quotes within a JS line are balanced (even count after
 * removing escaped quotes). Refuses lines with odd quote counts
 * that would break the always-valid invariant.
 */
function hasBalancedQuotes(s: string): boolean {
  const noEscaped = s.replace(/\\['"`]/g, '');
  const singleQuotes = (noEscaped.match(/'/g) || []).length;
  const doubleQuotes = (noEscaped.match(/"/g) || []).length;
  const backticks = (noEscaped.match(/`/g) || []).length;
  return singleQuotes % 2 === 0 && doubleQuotes % 2 === 0 && backticks % 2 === 0;
}

function sanitizeJsLine(raw: string): string {
  if (typeof raw !== 'string') return `// (invalid step: non-string arg)`;
  // Strip leading/trailing whitespace
  let s = raw.trim();
  // Reject newlines (would break "one statement per line" invariant)
  if (/[\r\n]/.test(s)) return `// (skipped step: contains newline)`;
  // Reject obviously incomplete lines
  if (s.length === 0) return `// (skipped step: empty)`;
  // Reject unbalanced quotes (would break JS syntax)
  if (!hasBalancedQuotes(s)) return `// (skipped step: unbalanced quotes)`;
  // Truncate absurdly long lines
  if (s.length > 500) s = s.slice(0, 500) + ' // (truncated)';
  // Add trailing semicolon if not present and the line looks like a statement
  if (!/[;{}\]\)]\s*$/.test(s) && !s.startsWith('//') && !s.startsWith('await expect')) {
    s = s + ';';
  }
  return s;
}
