/**
 * src/explorer/playwright-stream-writer.ts
 *
 * Live-streaming Playwright documentation writer.
 *
 * As the swarm runs, every macro step (browser action) and worker action
 * (HTTP request) is appended to a `replay.spec.ts` file in the output
 * directory. Each step is preceded by a decision comment that explains
 * WHY the agent took that action (Tier 3 of the Playwright-as-documentation
 * plan).
 *
 * Thread-safety: a single in-process write queue per scan serializes
 * concurrent appends from multiple workers. The file is always valid
 * Playwright syntax — `npx playwright test --list` works mid-scan.
 *
 * Three tiers of output:
 *   1. Regression tests (re-run findings to verify they still fail)
 *   2. Action replay (every action the swarm took, in order)
 *   3. Decision comments (LLM-generated or pre-computed explanation)
 */

import * as fsp from 'node:fs';
import * as pth from 'node:path';

export type StreamedEvent =
  | { kind: 'header'; agent: string; target: string; }
  | { kind: 'comment'; text: string; }
  | { kind: 'navigate'; url: string; }
  | { kind: 'click'; selector: string; }
  | { kind: 'fill'; selector: string; value: string; }
  | { kind: 'http_request'; method: string; url: string; payload: string; status: number; evidence: string[]; vulnerable: boolean; }
  | { kind: 'finding'; technique: string; endpoint: string; vulnerable: boolean; confidence: number; }
  | { kind: 'specialist_dispatch'; specialist: string; technique: string; endpoint: string; }
  | { kind: 'footer' };

export interface StreamerOptions {
  outputDir: string;
  target: string;
  agentName?: string;
  filename?: string;
}

export interface PlaywrightStreamer {
  push: (event: StreamedEvent) => Promise<void>;
  close: () => Promise<string>;
  filePath: string;
  pending: number;
}

const HEADER = `import { test, expect } from '@playwright/test';

/**
 * AUTO-GENERATED by Ultimatrix — live-streaming documentation.
 *
 * Tier 1: User Flow (recorded browser actions)
 * Tier 2: Swarm Action Replay (HTTP requests from workers)
 * Tier 3: Decision Comments (LLM-generated reasoning)
 *
 * This file is written incrementally as the scan runs.
 * Run "npx playwright test --list" at any point during a scan.
 */

test.describe('Ultimatrix Swarm Replay', () => {
`;

const FOOTER = `});
`;

const DANGER_PATTERN = /delete|destroy|logout|password|secret|token/i;

function escapeQuotes(s: string): string {
  if (s === undefined || s === null) return '';
  return String(s)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/`/g, '\\`')
    .replace(/\n/g, '\\n')
    .slice(0, 200);
}

function maskSensitive(value: string): string {
  if (DANGER_PATTERN.test(value)) return "'••••••••'";
  return `'${escapeQuotes(value)}'`;
}

function renderEvent(event: StreamedEvent, indent: string): string[] {
  const lines: string[] = [];
  if ('text' in event) {
    lines.push(`${indent}// ${event.text}`);
    return lines;
  }
  if (event.kind === 'navigate') {
    lines.push(`${indent}await page.goto('${escapeQuotes(event.url)}');`);
    return lines;
  }
  if (event.kind === 'click') {
    lines.push(`${indent}await page.click('${escapeQuotes(event.selector)}');`);
    return lines;
  }
  if (event.kind === 'fill') {
    lines.push(`${indent}await page.fill('${escapeQuotes(event.selector)}', ${maskSensitive(event.value)});`);
    return lines;
  }
  if (event.kind === 'http_request') {
    const vulnLabel = event.vulnerable ? ' [VULNERABLE]' : '';
    lines.push(`${indent}// Worker action: ${event.method} ${escapeQuotes(event.url)}${vulnLabel}`);
    lines.push(`${indent}test('${escapeQuotes(event.kind)} ${escapeQuotes(event.url.slice(0, 60))}', async ({ request }) => {`);
    lines.push(`${indent}  const res = await request.${event.method.toLowerCase()}('${escapeQuotes(event.url)}', {`);
    if (event.method !== 'GET' && event.payload) {
      lines.push(`${indent}    data: ${maskSensitive(event.payload)},`);
    }
    lines.push(`${indent}  });`);
    lines.push(`${indent}  expect(res.status()).toBeGreaterThanOrEqual(200);`);
    for (const ev of event.evidence.slice(0, 3)) {
      lines.push(`${indent}  // Evidence: ${escapeQuotes(ev.slice(0, 100))}`);
    }
    lines.push(`${indent}});`);
    return lines;
  }
  if (event.kind === 'finding') {
    const v = event.vulnerable ? '✓ VULNERABLE' : '✗ NOT VULNERABLE';
    lines.push(`${indent}// ──── Finding: ${event.technique} on ${event.endpoint} (${v}, confidence ${(event.confidence * 100).toFixed(0)}%)`);
    return lines;
  }
  if (event.kind === 'specialist_dispatch') {
    lines.push(`${indent}// → Dispatched ${event.specialist} for ${event.technique} on ${event.endpoint}`);
    return lines;
  }
  if (event.kind === 'header') {
    lines.push(`${indent}// Agent: ${event.agent}`);
    lines.push(`${indent}// Target: ${event.target}`);
    lines.push(`${indent}// Generated: ${new Date().toISOString()}`);
    return lines;
  }
  if (event.kind === 'footer') {
    lines.push(`});`);
    return lines;
  }
  return lines;
}

export class StreamWriter {
  private outputDir: string;
  private filePath: string;
  private target: string;
  private agentName: string;
  private queue: Promise<void> = Promise.resolve();
  private pending = 0;
  private closed = false;
  private hasOpened = false;

  constructor(opts: StreamerOptions) {
    this.outputDir = opts.outputDir;
    this.target = opts.target;
    this.agentName = opts.agentName || 'ultimatrix-swarm';
    this.filePath = pth.join(opts.outputDir, opts.filename || 'replay.spec.ts');
    fsp.mkdirSync(this.outputDir, { recursive: true });
  }

  get pendingCount(): number {
    return this.pending;
  }

  get path(): string {
    return this.filePath;
  }

  async push(event: StreamedEvent): Promise<void> {
    if (this.closed) throw new Error('Streamer already closed');
    this.pending++;
    this.queue = this.queue.then(() => this._write(event));
    return this.queue;
  }

  private async _write(event: StreamedEvent): Promise<void> {
    try {
      if (!this.hasOpened) {
        await fsp.promises.writeFile(this.filePath, HEADER, 'utf-8');
        const headerEvent: StreamedEvent = { kind: 'header', agent: this.agentName, target: this.target };
        const lines = renderEvent(headerEvent, '  ');
        await fsp.promises.appendFile(this.filePath, lines.join('\n') + '\n', 'utf-8');
        this.hasOpened = true;
      }
      const lines = renderEvent(event, '    ');
      if (lines.length > 0) {
        await fsp.promises.appendFile(this.filePath, lines.join('\n') + '\n', 'utf-8');
      }
    } finally {
      this.pending--;
    }
  }

  async close(): Promise<string> {
    await this.queue;
    if (!this.closed) {
      await fsp.promises.appendFile(this.filePath, FOOTER, 'utf-8');
      this.closed = true;
    }
    return this.filePath;
  }
}

export async function streamPlaywrightDoc(opts: StreamerOptions): Promise<PlaywrightStreamer> {
  const writer = new StreamWriter(opts);
  return {
    push: (event) => writer.push(event),
    close: () => writer.close(),
    filePath: writer.path,
    pending: 0,
  };
}
