// Generated by Ultimatrix — regression test for 8baa0c98-a68d-4129-ae4f-683dc58865ee
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding 8baa0c98-a68d-4129-ae4f-683dc58865ee — xss-v3 @ https://xss-game.appspot.com/level1/frame?query=Enter+query+here...', () => {
  const finding = findingsById.get("8baa0c98-a68d-4129-ae4f-683dc58865ee") || findings[0];

  test('reproduces xss-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("https://xss-game.appspot.com/level1/frame?query=Enter+query+here...");
    expect(res.status()).toBeLessThan(500);
  });
});
