// Generated by Ultimatrix — regression test for 710d0c47-6171-4891-933b-4b308721bfa0
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding 710d0c47-6171-4891-933b-4b308721bfa0 — xss-v3 @ https://xss-game.appspot.com/level1/frame?query=Enter+query+here...', () => {
  const finding = findingsById.get("710d0c47-6171-4891-933b-4b308721bfa0") || findings[0];

  test('reproduces xss-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("https://xss-game.appspot.com/level1/frame?query=Enter+query+here...");
    expect(res.status()).toBeLessThan(500);
  });
});
