// Generated by Ultimatrix — regression test for 7bdadea0-d14b-4176-baa8-e3c612e1e532
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding 7bdadea0-d14b-4176-baa8-e3c612e1e532 — xss-v3 @ https://xss-game.appspot.com/level1/source', () => {
  const finding = findingsById.get("7bdadea0-d14b-4176-baa8-e3c612e1e532") || findings[0];

  test('reproduces xss-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("https://xss-game.appspot.com/level1/source");
    expect(res.status()).toBeLessThan(500);
  });
});
