// Generated by Ultimatrix — regression test for f414c655-5149-4b03-bf64-d3b67a4fa703
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding f414c655-5149-4b03-bf64-d3b67a4fa703 — xss-v3 @ https://xss-game.appspot.com/level1/frame', () => {
  const finding = findingsById.get("f414c655-5149-4b03-bf64-d3b67a4fa703") || findings[0];

  test('reproduces xss-v3', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.get("https://xss-game.appspot.com/level1/frame");
    expect(res.status()).toBeLessThan(500);
  });
});
