// Generated by Ultimatrix — do not edit by hand
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: '.',
  timeout: 30_000,
  reporter: [['list'], ['json', { outputFile: 'attack-results.json' }]],
  use: {
    baseURL: "https://xss-game.appspot.com/",
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    actionTimeout: 8_000,
    navigationTimeout: 15_000,
  },
  fullyParallel: false,
  workers: 1,
  retries: 0,
});
