import { TraceEntry, MacroStep } from './browser-session';
import type { WorkerAction } from './app-model';
import * as fsp from 'node:fs';
import * as pth from 'node:path';

export function traceToHar(trace: TraceEntry[]): string {
  const entries = trace.map((t, i) => ({
    startedDateTime: new Date(t.timestamp).toISOString(),
    time: t.duration,
    request: {
      method: t.method,
      url: t.url,
      httpVersion: 'HTTP/1.1',
      headers: Object.entries(t.requestHeaders).map(([name, value]) => ({ name, value })),
      queryString: [],
      cookies: [],
      headersSize: -1,
      bodySize: t.requestBody?.length ?? -1,
    },
    response: {
      status: t.status,
      statusText: '',
      httpVersion: 'HTTP/1.1',
      headers: Object.entries(t.responseHeaders).map(([name, value]) => ({ name, value })),
      cookies: [],
      content: {
        size: -1,
        mimeType: t.responseHeaders['content-type'] || '',
      },
      redirectURL: '',
      headersSize: -1,
      bodySize: -1,
    },
    cache: {},
    timings: { send: 0, wait: t.duration, receive: 0 },
    pageref: t.sourcePage || `page_${i}`,
  }));

  return JSON.stringify({ log: { version: '1.2', creator: { name: 'ultimatrix', version: '1.0' }, entries } }, null, 2);
}

export interface CrawlDocData {
  routes: Array<{ url: string; title: string; forms: number; links: number }>;
  forms: Array<{ pageUrl: string; action: string; fields: Array<{ name: string; type: string }> }>;
  totalRoutes: number;
  auth: { type: string; loginEndpoint: string };
  techStack: string[];
}

export interface GenerateTestOptions {
  steps: MacroStep[];
  target: string;
  outputDir: string;
  totalRoutes?: number;
  filename?: string;
}

export function generatePlaywrightTest(opts: GenerateTestOptions): { filePath: string; stepCount: number } {
  if (!opts.steps.length) {
    return { filePath: '', stepCount: 0 };
  }

  const lines: string[] = [
    `import { test } from '@playwright/test';`,
    ``,
    `test('recorded flow: ${opts.target}', async ({ page }) => {`,
  ];

  let screenshotIndex = 1;
  for (const step of opts.steps) {
    switch (step.type) {
      case 'navigate':
        lines.push(`  await page.goto('${escapeQuotes(step.url || opts.target)}');`);
        break;
      case 'click':
        lines.push(`  await page.click('${escapeQuotes(step.selector || '')}');`);
        break;
      case 'fill':
        lines.push(`  await page.fill('${escapeQuotes(step.selector || '')}', '${escapeQuotes(step.value || '')}');`);
        break;
      case 'wait':
        lines.push(`  await page.waitForTimeout(${step.waitMs || 1000});`);
        break;
      case 'screenshot':
        lines.push(`  await page.screenshot({ path: 'step-${screenshotIndex}.png' });`);
        screenshotIndex++;
        break;
      case 'evaluate':
        lines.push(`  await page.evaluate(\`${escapeQuotes(step.script || '')}\`);`);
        break;
    }
  }

  lines.push(`});`);
  lines.push('');

  const filename = opts.filename || `flow-${Date.now()}.spec.ts`;
  const filePath = pth.join(opts.outputDir, filename);
  fsp.writeFileSync(filePath, lines.join('\n'), 'utf-8');
  return { filePath, stepCount: opts.steps.length };
}

export function generateSecurityPlaywrightTest(opts: {
  browserSteps: MacroStep[];
  workerActions: WorkerAction[];
  target: string;
  outputDir: string;
  docData?: CrawlDocData;
}): string[] {
  fsp.mkdirSync(opts.outputDir, { recursive: true });
  const files: string[] = [];

  if (opts.browserSteps.length === 0 && opts.workerActions.length === 0 && !opts.docData) {
    return files;
  }

  const L: string[] = [
    `import { test, expect } from '@playwright/test';`,
    ``,
    `// Auto-generated by Ultimatrix`,
    `// Target: ${opts.target}`,
    `// Generated: ${new Date().toISOString()}`,
    ``,
    `test.describe('Security Assessment: ${escapeQuotes(opts.target)}', () => {`,
  ];

  const e = escapeQuotes;

  // ════════════════════════════════════════════════════════════════
  // USER FLOW — Natural browsing experience
  // ════════════════════════════════════════════════════════════════
  if (opts.browserSteps.length > 0) {
    L.push(``);
    L.push(`  // ════════════════════════════════════════════`);
    L.push(`  // USER FLOW — how a person would browse the application`);
    L.push(`  // ${opts.browserSteps.length} interaction(s) replayed in natural order`);
    L.push(`  // ════════════════════════════════════════════`);
    L.push(``);
    L.push(`  test.describe('User Flow', () => {`);
    L.push(`    test('browse as a real user', async ({ page }) => {`);

    for (let i = 0; i < opts.browserSteps.length; i++) {
      const step = opts.browserSteps[i];
      const next = i + 1 < opts.browserSteps.length ? opts.browserSteps[i + 1] : null;
      const prev = i > 0 ? opts.browserSteps[i - 1] : null;

      // Check for form fill group: fill* + click(submit) or fill* + navigate
      if (step.type === 'navigate') {
        const url = step.url || opts.target;
        if (prev && prev.type !== 'navigate') {
          L.push(`      // ---`);
        }
        L.push(`      // Go to ${e(extractPath(url))}`);
        L.push(`      await page.goto('${e(url)}');`);
      } else if (step.type === 'fill') {
        const isPassword = /password|passwd|pwd/i.test(step.selector || '');
        const val = isPassword ? `'••••••••'` : `'${e(step.value || '')}'`;

        // Look ahead: if next step is also fill, group them with a single comment
        if (!prev || prev.type !== 'fill') {
          L.push(`      // Fill in form fields`);
        }
        L.push(`      await page.fill('${e(step.selector || '')}', ${val});`);

        // If next step is a click (likely submit), add submit comment
        if (next && next.type === 'click') {
          L.push(`      // Submit form`);
          L.push(`      await page.click('${e(next.selector || '')}');`);
          i++; // skip next step since we handled it
        } else if (next && next.type === 'navigate') {
          L.push(`      // ---`);
        }
      } else if (step.type === 'click') {
        // Only emit if next step isn't fill (already handled above)
        if (!prev || prev.type !== 'fill') {
          L.push(`      await page.click('${e(step.selector || '')}');`);
        }
      } else if (step.type === 'wait') {
        L.push(`      await page.waitForTimeout(${step.waitMs || 1000});`);
      } else if (step.type === 'screenshot') {
        L.push(`      await page.screenshot({ path: 'user-flow.png' });`);
      } else if (step.type === 'evaluate') {
        L.push(`      await page.evaluate(\`${e(step.script || '')}\`);`);
      }
    }

    L.push(`    });`);
    L.push(`  });`);
  }

  // ════════════════════════════════════════════════════════════════
  // ASSESS FLOW — Systematic security assessment
  // ════════════════════════════════════════════════════════════════
  const dbg = opts.docData;
  const hasRoutes = dbg && dbg.routes.length > 0;
  const hasVuln = opts.workerActions.some((a) => a.vulnerable);
  const hasClean = opts.workerActions.some((a) => !a.vulnerable);

  if (hasRoutes || hasVuln || hasClean) {
    L.push(``);
    L.push(`  // ════════════════════════════════════════════`);
    L.push(`  // ASSESS FLOW — how the scanner observed and tested the application`);
    L.push(`  // ${hasRoutes ? dbg!.totalRoutes + ' route(s) discovered' : ''}${hasRoutes && hasVuln ? ', ' : ''}${hasVuln ? opts.workerActions.filter(a => a.vulnerable).length + ' finding(s)' : ''}${(hasRoutes || hasVuln) && hasClean ? ', ' : ''}${hasClean ? opts.workerActions.filter(a => !a.vulnerable).length + ' clean endpoint(s)' : ''}`);
    L.push(`  // ════════════════════════════════════════════`);
    L.push(``);
    L.push(`  test.describe('Assessment Flow', () => {`);

    // ── 2A: Route Discovery ──
    if (hasRoutes) {
      L.push(``);
      L.push(`    // ── Route Discovery ──`);
      L.push(`    // Every page found during crawl, with structure summary`);
      L.push(`    test.describe('Route Discovery', () => {`);

      for (let i = 0; i < dbg!.routes.length; i++) {
        const r = dbg!.routes[i];
        const formDetail =
          dbg!.forms.filter((f) => f.pageUrl === r.url).length > 0
            ? dbg!.forms
                .filter((f) => f.pageUrl === r.url)
                .map((f) => f.fields.map((fd) => `${fd.name}:${fd.type}`).join(', '))
                .join(' | ')
            : 'no forms';
        const label = `GET ${extractPath(r.url) || '/'} — ${r.title || 'untitled'}`.slice(0, 80);
        L.push(`      test('${e(label)}', async ({ page }) => {`);
        L.push(`        await page.goto('${e(r.url)}');`);
        L.push(`        await expect(page).toHaveTitle(/./);`);
        L.push(`        // ${r.forms} form(s), fields: [${e(formDetail)}]`);
        L.push(`      });`);
      }

      L.push(`    });`);
    }

    // ── 2B: Attack Replay ──
    const vulnerable = opts.workerActions.filter((a) => a.vulnerable);
    const endpoints = new Map<string, WorkerAction[]>();
    for (const a of vulnerable) {
      const key = `${a.method} ${a.url}`;
      if (!endpoints.has(key)) endpoints.set(key, []);
      endpoints.get(key)!.push(a);
    }

    if (vulnerable.length > 0) {
      L.push(``);
      L.push(`    // ── Attack Replay — Regression Suite ──`);
      L.push(`    // ${vulnerable.length} finding(s) across ${endpoints.size} endpoint(s)`);

      for (const [endpoint, attempts] of endpoints) {
        const techs = [...new Set(attempts.map((a) => a.technique))];
        L.push(`    test.describe('${e(endpoint.slice(0, 80))} [${techs.join(', ')}]', () => {`);

        for (const attempt of attempts) {
          const payloadSnippet = attempt.payload.slice(0, 60);
          const evidenceSummary = attempt.evidence.slice(0, 2).map((ev) => ev.slice(0, 60)).join(', ');
          L.push(`      test('${e(attempt.technique)} (attempt ${attempt.attempt})', async ({ page }) => {`);
          L.push(`        // Payload: ${e(payloadSnippet)}`);
          L.push(`        // Evidence: ${e(evidenceSummary)}`);
          L.push(`        const res = await page.request.${attempt.method.toLowerCase()}('${e(attempt.url)}', {`);

          if (attempt.method !== 'GET') {
            L.push(`          data: '${e(attempt.payload)}',`);
            L.push(`          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },`);
          } else {
            L.push(`          params: { q: '${e(attempt.payload)}' },`);
          }

          L.push(`        });`);
          L.push(`        expect(res.status()).toBe(${attempt.status});`);
          L.push(`        const body = await res.text();`);

          for (const evidence of attempt.evidence) {
            L.push(`        expect(body).toContain('${e(evidence.slice(0, 100))}');`);
          }

          L.push(`      });`);
        }

        L.push(`    });`);
      }
    }

    // ── 2C: Clean Endpoints ──
    const nonVulnerable = opts.workerActions.filter((a) => !a.vulnerable);
    if (nonVulnerable.length > 0) {
      L.push(``);
      L.push(`    // ── Tested Endpoints (No Finding) ──`);
      L.push(`    // ${nonVulnerable.length} attempt(s) tested — no evidence of vulnerability detected`);

      const cleanByTech = new Map<string, WorkerAction[]>();
      for (const a of nonVulnerable) {
        if (!cleanByTech.has(a.technique)) cleanByTech.set(a.technique, []);
        cleanByTech.get(a.technique)!.push(a);
      }

      for (const [tech, attempts] of cleanByTech) {
        L.push(`    test.describe('${e(tech)} — ${attempts.length} attempt(s)', () => {`);
        for (const attempt of attempts) {
          L.push(`      test('${e(attempt.method)} ${e(extractPath(attempt.url))} — no finding', async ({ page }) => {`);
          L.push(`        // Payload tested: ${e(attempt.payload.slice(0, 80))}`);
          L.push(`        // No matching evidence in response`);
          L.push(`        const res = await page.request.${attempt.method.toLowerCase()}('${e(attempt.url)}', {`);

          if (attempt.method !== 'GET') {
            L.push(`          data: '${e(attempt.payload)}',`);
            L.push(`          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },`);
          } else {
            L.push(`          params: { q: '${e(attempt.payload)}' },`);
          }

          L.push(`        });`);
          L.push(`        expect(res.status()).toBeGreaterThanOrEqual(200);`);
          L.push(`        expect(res.status()).toBeLessThan(500);`);
          L.push(`      });`);
        }
        L.push(`    });`);
      }
    }

    L.push(`  });`);
  }

  L.push(`});`);
  L.push('');

  const filename = `assess-flow.spec.ts`;
  const filePath = pth.join(opts.outputDir, filename);
  fsp.writeFileSync(filePath, L.join('\n'), 'utf-8');
  files.push(filename);

  return files;
}

function extractPath(url: string): string {
  try {
    const u = new URL(url);
    return u.pathname + u.search + u.hash;
  } catch {
    return url;
  }
}

function escapeQuotes(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/`/g, '\\`').replace(/\$/g, '\\$');
}
