// Generated by Ultimatrix — do not edit by hand
import type { AppModelFinding } from '../../src/core/app-model';

export interface FindingFixture {
  id: string;
  type: string;
  severity: string;
  endpoint: string;
  method: string;
  param: string;
  payload: string;
  confidence: number;
  description: string;
}

export const findings: FindingFixture[] = [
  {
    id: "06c417bb-10b0-483f-a7a4-b386265b2fe4",
    type: "xss-v3",
    severity: "medium",
    endpoint: "https://xss-game.appspot.com/level1/frame?query=Enter+query+here...",
    method: "GET",
    param: "",
    payload: "",
    confidence: "high",
    description: "",
  }
];

export const findingsById = new Map(findings.map((f) => [f.id, f]));
export const findingsBySeverity = (s: string) => findings.filter((f) => f.severity === s);
export const findingsByType = (t: string) => findings.filter((f) => f.type === t);
