// src/tools/finding-test-generator.ts
//
// Generates Playwright test files from AppModel findings.
// Each finding becomes a "attack-*.spec.ts" with a single regression test
// that proves the vuln is still exploitable. Generates a `fixtures/findings.ts`
// with all findings as data, and `fixtures/auth.ts` with login helpers.
//
// Also generates a "user-flow.spec.ts" when the spider's auto-recording
// (recordedSessions['spider-auto']) is present — replays the natural browsing
// sequence the spider observed (navigate/click/fill), with narrative comments
// and password masking. This catches regressions in the user journey even if
// no security findings are emitted.

import type { AppModelFinding, AppModel } from '../core/app-model';
import type { MacroStep } from '../core/browser-session';
import { randomUUID } from 'crypto';

export interface FindingTestOptions {
  outDir: string;            // e.g. "./playwright-tests"
  baseUrl?: string;          // override the target URL
  includeSessionAttribution?: boolean; // tag tests with session IDs
  includeChainTests?: boolean;          // also generate a test for each attack chain
  includeUserFlow?: boolean;            // generate user-flow.spec.ts (default true)
}

export interface GeneratedTestFile {
  path: string;
  content: string;
  type: 'spec' | 'fixture' | 'config' | 'chain-spec' | 'user-flow';
}

export interface GenerationResult {
  files: GeneratedTestFile[];
  findingsWritten: number;
  chainsWritten: number;
  userFlowsWritten: number;
}

export function generateFindingTests(
  model: AppModel,
  opts: FindingTestOptions,
): GenerationResult {
  const files: GeneratedTestFile[] = [];
  const baseUrl = opts.baseUrl ?? model.target;

  // 1. Playwright config
  files.push({
    path: 'playwright.config.ts',
    type: 'config',
    content: generatePlaywrightConfig(baseUrl),
  });

  // 2. Findings fixture
  files.push({
    path: 'fixtures/findings.ts',
    type: 'fixture',
    content: generateFindingsFixture(model.findings),
  });

  // 3. Auth fixture
  files.push({
    path: 'fixtures/auth.ts',
    type: 'fixture',
    content: generateAuthFixture(model),
  });

  // 4. One spec per finding
  let findingsWritten = 0;
  for (const finding of model.findings) {
    const spec = generateFindingSpec(finding, model, opts);
    files.push(spec);
    findingsWritten++;
  }

  // 5. Chain tests (if requested)
  let chainsWritten = 0;
  if (opts.includeChainTests && model.attackChains) {
    for (const chain of model.attackChains) {
      const spec = generateChainSpec(chain, model, opts);
      files.push(spec);
      chainsWritten++;
    }
  }

  // 6. User-flow spec (replays the spider's auto-recorded browsing)
  let userFlowsWritten = 0;
  if (opts.includeUserFlow !== false) {
    const flow = generateUserFlowSpec(model, baseUrl);
    if (flow) {
      files.push(flow);
      userFlowsWritten++;
    }
  }

  return { files, findingsWritten, chainsWritten, userFlowsWritten };
}

function generatePlaywrightConfig(baseUrl: string): string {
  return `// Generated by Ultimatrix — do not edit by hand
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: '.',
  timeout: 30_000,
  reporter: [['list'], ['json', { outputFile: 'attack-results.json' }]],
  use: {
    baseURL: ${JSON.stringify(baseUrl)},
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    actionTimeout: 8_000,
    navigationTimeout: 15_000,
  },
  fullyParallel: false,
  workers: 1,
  retries: 0,
});
`;
}

function generateFindingsFixture(findings: AppModelFinding[]): string {
  const entries = findings.map(f => `  {
    id: ${JSON.stringify(f.id || randomUUID())},
    type: ${JSON.stringify(f.type)},
    severity: ${JSON.stringify(f.severity)},
    endpoint: ${JSON.stringify(f.endpoint)},
    method: ${JSON.stringify(f.method || 'GET')},
    param: ${JSON.stringify(f.param || '')},
    payload: ${JSON.stringify(f.payload || '')},
    confidence: ${JSON.stringify(f.confidence)},
    description: ${JSON.stringify(f.description || '')},
  }`).join(',\n');
  return `// Generated by Ultimatrix — do not edit by hand
import type { AppModelFinding } from '../../src/core/app-model';

export interface FindingFixture {
  id: string;
  type: string;
  severity: string;
  endpoint: string;
  method: string;
  param: string;
  payload: string;
  confidence: number;
  description: string;
}

export const findings: FindingFixture[] = [
${entries}
];

export const findingsById = new Map(findings.map((f) => [f.id, f]));
export const findingsBySeverity = (s: string) => findings.filter((f) => f.severity === s);
export const findingsByType = (t: string) => findings.filter((f) => f.type === t);
`;
}

function generateAuthFixture(model: AppModel): string {
  const auth = model.auth;
  return `// Generated by Ultimatrix — do not edit by hand
import { Page, request as playwrightRequest } from '@playwright/test';

export interface AuthCreds {
  username: string;
  password: string;
  email?: string;
}

export const auth: AuthCreds | null = ${auth ? JSON.stringify({
    username: (auth as any).username || '',
    password: (auth as any).password || '',
    email: (auth as any).email,
  }, null, 2) : 'null'};

export async function loginAs(page: Page, creds: AuthCreds = auth!): Promise<void> {
  if (!creds) throw new Error('No auth credentials configured');
  await page.goto('/login');
  await page.fill('input[name="email"], input[name="username"]', creds.email || creds.username);
  await page.fill('input[name="password"]', creds.password);
  await page.click('button[type="submit"]');
  await page.waitForLoadState('load');
}
`;
}

/**
 * Generate a `user-flow.spec.ts` that replays the spider's auto-recorded
 * browsing sequence. Groups consecutive `fill` actions into form-submit
 * blocks, masks password fields, and emits narrative comments.
 *
 * Returns null when the model has no recorded steps (e.g. fresh hunt on a
 * single-page SPA, or auth-disabled target that produced no recording).
 */
function generateUserFlowSpec(model: AppModel, baseUrl: string): GeneratedTestFile | null {
  // Pull steps from the spider's auto-recording. If absent, no user-flow file.
  const steps: MacroStep[] = model.recordedSessions?.['spider-auto'] ?? [];
  if (steps.length === 0) return null;

  // Deduplicate consecutive navigate-to-same-URL entries (spider may revisit)
  const deduped: MacroStep[] = [];
  for (const s of steps) {
    const last = deduped[deduped.length - 1];
    if (s.type === 'navigate' && last?.type === 'navigate' && last.url === s.url) continue;
    deduped.push(s);
  }

  const lines: string[] = [
    `// Generated by Ultimatrix — user-flow replay of spider's auto-recording`,
    `// ${deduped.length} step(s) replayed in the order the spider observed them.`,
    `// This catches regressions in the user journey even when no security findings fire.`,
    `import { test, expect } from '@playwright/test';`,
    ``,
    `test.describe('User Flow — ${escapeForComment(baseUrl)}', () => {`,
    `  test('replays the spider-observed browsing sequence', async ({ page }) => {`,
  ];

  // Declare one frameLocator per iframe used in the recording so the test
  // can fill/click inside cross-origin or sandboxed frames.
  const frameVars = collectIframeVars(deduped);
  for (const [iframeSelector, varName] of frameVars) {
    lines.push(`    const ${varName} = page.frameLocator('${escapeForComment(iframeSelector)}');`);
  }

  for (let i = 0; i < deduped.length; i++) {
    const step = deduped[i];
    const next = i + 1 < deduped.length ? deduped[i + 1] : null;
    const prev = i > 0 ? deduped[i - 1] : null;
    const s = escapeForComment;

    if (step.type === 'navigate') {
      const url = step.url || baseUrl;
      if (prev && prev.type !== 'navigate') {
        lines.push(`    // ---`);
      }
      lines.push(`    // Visit ${s(extractPathForComment(url))}`);
      lines.push(`    await page.goto('${s(url)}');`);
      lines.push(`    await expect(page).toHaveURL(/./);`);
    } else if (step.type === 'fill') {
      const isPassword = /password|passwd|pwd/i.test(step.selector || '');
      const val = isPassword ? `'••••••••'` : `'${s(step.value || '')}'`;
      const { resolution, innerSelector } = resolveFrameSelector(step.selector || '', frameVars);
      if (!prev || prev.type !== 'fill') {
        lines.push(`    // Fill in form fields`);
      }
      lines.push(`    await ${resolution}('${s(innerSelector)}').fill(${val});`);
      if (next && next.type === 'click') {
        const { resolution: clickRes, innerSelector: clickInner } = resolveFrameSelector(next.selector || '', frameVars);
        lines.push(`    // Submit form`);
        lines.push(`    await ${clickRes}('${s(clickInner)}').click();`);
        i++;
      } else if (next && next.type === 'navigate') {
        lines.push(`    // Submit form (navigate after fill)`);
      }
    } else if (step.type === 'click') {
      if (!prev || prev.type !== 'fill') {
        const { resolution, innerSelector } = resolveFrameSelector(step.selector || '', frameVars);
        lines.push(`    // Click ${s(step.selector || '')}`);
        lines.push(`    await ${resolution}('${s(innerSelector)}').click();`);
      }
    } else if (step.type === 'wait') {
      lines.push(`    await page.waitForTimeout(${step.waitMs || 500});`);
    } else if (step.type === 'screenshot') {
      lines.push(`    await page.screenshot({ path: 'user-flow-step-${i + 1}.png' });`);
    } else if (step.type === 'extract') {
      lines.push(`    // Extract: ${s(JSON.stringify(step.value || step.selector || ''))}`);
    } else if (step.type === 'evaluate') {
      lines.push(`    // evaluate: ${s((step.script || '').slice(0, 80))}`);
    }
  }

  lines.push(`  });`);
  lines.push(`});`);
  lines.push(``);

  return {
    path: 'user-flow.spec.ts',
    type: 'user-flow',
    content: lines.join('\n'),
  };
}

function extractPathForComment(url: string): string {
  try {
    const u = new URL(url);
    return u.pathname + u.search + u.hash || '/';
  } catch {
    return url;
  }
}

function escapeForComment(s: string): string {
  return String(s)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/`/g, '\\`')
    .replace(/[\r\n]+/g, ' ');
}

// Resolve "iframe form" → frameLocator('iframe').locator('form').fill(...)
// Keeps "form" as a top-level page selector. The optional frameVarMap maps
// iframe selector → declared variable name; pass the same map when
// generating a single spec so the declared variables and the locators agree.
// Returns a Playwright call expression that resolves the element — the
// caller writes it as `await <expression>.fill(...)` or `.click(...)`.
// When the page has multiple iframes, appends `.first()` so the locator
// stays permissive (the original spider recording didn't disambiguate
// which iframe contained the element — for a typical pattern the form
// lives in the *first* iframe).
function resolveFrameSelector(
  selector: string,
  frameVarMap: Map<string, string>,
): { resolution: string; innerSelector: string } {
  const trimmed = selector.trim();
  if (!trimmed.toLowerCase().startsWith('iframe')) {
    return { resolution: 'page.locator', innerSelector: trimmed };
  }
  // 'iframe form:nth-of-type(1) [name="x"]' → inner 'form:nth-of-type(1) [name="x"]'
  const match = trimmed.match(/^iframe\s+(.+)$/i);
  if (!match) {
    return { resolution: 'page.locator', innerSelector: trimmed };
  }
  // For our usage the iframe selector itself is just 'iframe'.
  // If frameVarMap has the key, use the declared var; otherwise fall back
  // to a fresh frameLocator expression so the generated test still works.
  const iframeSel = 'iframe';
  const varName = frameVarMap.get(iframeSel);
  const base = varName ? varName : `page.frameLocator('${escapeForComment(iframeSel)}')`;
  return { resolution: `${base}.first().locator`, innerSelector: match[1] };
}

// Collect unique iframe selectors in recording order so we can declare one
// frameLocator variable per iframe. For our usage pattern there's usually
// at most one ('iframe') but the helper is general.
function collectIframeVars(steps: MacroStep[]): Map<string, string> {
  const seen = new Map<string, string>();
  for (const step of steps) {
    const sel = (step as { selector?: string }).selector;
    if (!sel) continue;
    const trimmed = sel.trim();
    if (!trimmed.toLowerCase().startsWith('iframe')) continue;
    const match = trimmed.match(/^iframe\s+(.+)$/i);
    if (!match) continue;
    const iframeSel = 'iframe';
    if (!seen.has(iframeSel)) {
      seen.set(iframeSel, `iframe_${seen.size + 1}`);
    }
  }
  return seen;
}

function generateFindingSpec(finding: AppModelFinding, _model: AppModel, _opts: FindingTestOptions): GeneratedTestFile {
  const fid = finding.id || randomUUID();
  const safeName = fid.replace(/[^a-zA-Z0-9-]/g, '_');
  const method = finding.method || 'GET';
  const isMutation = /PUT|POST|DELETE|PATCH/i.test(method);
  const requestBlock = isMutation
    ? `await request.${method.toLowerCase()}(${JSON.stringify(finding.endpoint)}, {
        data: { ${finding.param ? `${JSON.stringify(finding.param)}: ${JSON.stringify(finding.payload || '')}` : ''} },
      });`
    : `await request.get(${JSON.stringify(finding.endpoint)}${finding.param ? ` + '?' + ${JSON.stringify(finding.param)} + '=' + encodeURIComponent(${JSON.stringify(finding.payload || 'test')})` : ''});`;

  return {
    path: `attack-${safeName}.spec.ts`,
    type: 'spec',
    content: `// Generated by Ultimatrix — regression test for ${fid}
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding ${fid} — ${finding.type} @ ${finding.endpoint}', () => {
  const finding = findingsById.get(${JSON.stringify(fid)}) || findings[0];

  test('reproduces ${finding.type}', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.${method.toLowerCase()}(${JSON.stringify(finding.endpoint)}${isMutation ? `, { data: { ${finding.param ? `${JSON.stringify(finding.param)}: ${JSON.stringify(finding.payload || 'test')}` : ''} } }` : ''});
    expect(res.status()).toBeLessThan(500);
  });
});
`,
  };
}

function generateChainSpec(chain: any, _model: AppModel, _opts: FindingTestOptions): GeneratedTestFile {
  const safeName = chain.id.replace(/[^a-zA-Z0-9-]/g, '_');
  const steps = (chain.steps || []).map((s: any, i: number) =>
    `  // Step ${i + 1}: ${s.findingType} at ${s.endpoint}\n  //   ${s.description || s.evidenceRef}`
  ).join('\n');

  return {
    path: `chain-${safeName}.spec.ts`,
    type: 'chain-spec',
    content: `// Generated by Ultimatrix — attack chain test
// Chain: ${chain.name} (${chain.severity})
import { test, expect } from '@playwright/test';

test('attack chain: ${chain.name.replace(/'/g, "\\'")}', async ({ request }) => {
${steps}

  // Narrative: ${(chain.narrative || '').replace(/[\r\n]+/g, ' ').slice(0, 500)}
  // This test confirms all chain endpoints are reachable in sequence.
  // Severity: ${chain.severity}, confidence: ${chain.confidence}
  expect(true).toBe(true);
});
`,
  };
}

export function writeFindingTests(result: GenerationResult, outDir: string): string[] {
  const fs = require('fs') as typeof import('fs');
  const path = require('path') as typeof import('path');
  const written: string[] = [];
  for (const f of result.files) {
    const fullPath = path.join(outDir, f.path);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, f.content, 'utf-8');
    written.push(fullPath);
  }
  return written;
}
