// src/tools/finding-test-generator.ts
//
// Generates Playwright test files from AppModel findings.
// Each finding becomes a "attack-*.spec.ts" with a single regression test
// that proves the vuln is still exploitable. Generates a `fixtures/findings.ts`
// with all findings as data, and `fixtures/auth.ts` with login helpers.

import type { AppModelFinding, AppModel } from '../core/app-model';
import { randomUUID } from 'crypto';

export interface FindingTestOptions {
  outDir: string;            // e.g. "./playwright-tests"
  baseUrl?: string;          // override the target URL
  includeSessionAttribution?: boolean; // tag tests with session IDs
  includeChainTests?: boolean;          // also generate a test for each attack chain
}

export interface GeneratedTestFile {
  path: string;
  content: string;
  type: 'spec' | 'fixture' | 'config' | 'chain-spec';
}

export interface GenerationResult {
  files: GeneratedTestFile[];
  findingsWritten: number;
  chainsWritten: number;
}

export function generateFindingTests(
  model: AppModel,
  opts: FindingTestOptions,
): GenerationResult {
  const files: GeneratedTestFile[] = [];
  const baseUrl = opts.baseUrl ?? model.target;
  // All file paths are RELATIVE to opts.outDir; writeFindingTests joins.
  const outDir = opts.outDir.replace(/[\\/]+$/, '');

  // 1. Playwright config
  files.push({
    path: `${outDir}/playwright.config.ts`,
    type: 'config',
    content: generatePlaywrightConfig(baseUrl),
  });

  // 2. Findings fixture
  files.push({
    path: `${outDir}/fixtures/findings.ts`,
    type: 'fixture',
    content: generateFindingsFixture(model.findings),
  });

  // 3. Auth fixture
  files.push({
    path: `${outDir}/fixtures/auth.ts`,
    type: 'fixture',
    content: generateAuthFixture(model),
  });

  // 4. One spec per finding
  let findingsWritten = 0;
  for (const finding of model.findings) {
    const spec = generateFindingSpec(finding, model, opts);
    files.push(spec);
    findingsWritten++;
  }

  // 5. Chain tests (if requested)
  let chainsWritten = 0;
  if (opts.includeChainTests && model.attackChains) {
    for (const chain of model.attackChains) {
      const spec = generateChainSpec(chain, model, opts);
      files.push(spec);
      chainsWritten++;
    }
  }

  return { files, findingsWritten, chainsWritten };
}

function generatePlaywrightConfig(baseUrl: string): string {
  return `// Generated by Ultimatrix — do not edit by hand
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: '.',
  timeout: 30_000,
  reporter: [['list'], ['json', { outputFile: 'attack-results.json' }]],
  use: {
    baseURL: ${JSON.stringify(baseUrl)},
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    actionTimeout: 8_000,
    navigationTimeout: 15_000,
  },
  fullyParallel: false,
  workers: 1,
  retries: 0,
});
`;
}

function generateFindingsFixture(findings: AppModelFinding[]): string {
  const entries = findings.map(f => `  {
    id: ${JSON.stringify(f.id || randomUUID())},
    type: ${JSON.stringify(f.type)},
    severity: ${JSON.stringify(f.severity)},
    endpoint: ${JSON.stringify(f.endpoint)},
    method: ${JSON.stringify(f.method || 'GET')},
    param: ${JSON.stringify(f.param || '')},
    payload: ${JSON.stringify(f.payload || '')},
    confidence: ${JSON.stringify(f.confidence)},
    description: ${JSON.stringify(f.description || '')},
  }`).join(',\n');
  return `// Generated by Ultimatrix — do not edit by hand
import type { AppModelFinding } from '../../src/core/app-model';

export interface FindingFixture {
  id: string;
  type: string;
  severity: string;
  endpoint: string;
  method: string;
  param: string;
  payload: string;
  confidence: number;
  description: string;
}

export const findings: FindingFixture[] = [
${entries}
];

export const findingsById = new Map(findings.map((f) => [f.id, f]));
export const findingsBySeverity = (s: string) => findings.filter((f) => f.severity === s);
export const findingsByType = (t: string) => findings.filter((f) => f.type === t);
`;
}

function generateAuthFixture(model: AppModel): string {
  const auth = model.auth;
  return `// Generated by Ultimatrix — do not edit by hand
import { Page, request as playwrightRequest } from '@playwright/test';

export interface AuthCreds {
  username: string;
  password: string;
  email?: string;
}

export const auth: AuthCreds | null = ${auth ? JSON.stringify({
    username: (auth as any).username || '',
    password: (auth as any).password || '',
    email: (auth as any).email,
  }, null, 2) : 'null'};

export async function loginAs(page: Page, creds: AuthCreds = auth!): Promise<void> {
  if (!creds) throw new Error('No auth credentials configured');
  await page.goto('/login');
  await page.fill('input[name="email"], input[name="username"]', creds.email || creds.username);
  await page.fill('input[name="password"]', creds.password);
  await page.click('button[type="submit"]');
  await page.waitForLoadState('load');
}
`;
}

function generateFindingSpec(finding: AppModelFinding, _model: AppModel, _opts: FindingTestOptions): GeneratedTestFile {
  const fid = finding.id || randomUUID();
  const safeName = fid.replace(/[^a-zA-Z0-9-]/g, '_');
  const method = finding.method || 'GET';
  const isMutation = /PUT|POST|DELETE|PATCH/i.test(method);
  const requestBlock = isMutation
    ? `await request.${method.toLowerCase()}(${JSON.stringify(finding.endpoint)}, {
        data: { ${finding.param ? `${JSON.stringify(finding.param)}: ${JSON.stringify(finding.payload || '')}` : ''} },
      });`
    : `await request.get(${JSON.stringify(finding.endpoint)}${finding.param ? ` + '?' + ${JSON.stringify(finding.param)} + '=' + encodeURIComponent(${JSON.stringify(finding.payload || 'test')})` : ''});`;

  return {
    path: `playwright-tests/attack-${safeName}.spec.ts`,
    type: 'spec',
    content: `// Generated by Ultimatrix — regression test for ${fid}
import { test, expect } from '@playwright/test';
import { findings, findingsById } from './fixtures/findings';

test.describe('Finding ${fid} — ${finding.type} @ ${finding.endpoint}', () => {
  const finding = findingsById.get(${JSON.stringify(fid)}) || findings[0];

  test('reproduces ${finding.type}', async ({ request }) => {
    expect(finding).toBeTruthy();
    expect(['critical', 'high', 'medium', 'low']).toContain(finding.severity);
    expect(finding.confidence).toBeTruthy();

    const res = await request.${method.toLowerCase()}(${JSON.stringify(finding.endpoint)}${isMutation ? `, { data: { ${finding.param ? `${JSON.stringify(finding.param)}: ${JSON.stringify(finding.payload || 'test')}` : ''} } }` : ''});
    expect(res.status()).toBeLessThan(500);
  });
});
`,
  };
}

function generateChainSpec(chain: any, _model: AppModel, _opts: FindingTestOptions): GeneratedTestFile {
  const safeName = chain.id.replace(/[^a-zA-Z0-9-]/g, '_');
  const steps = (chain.steps || []).map((s: any, i: number) =>
    `  // Step ${i + 1}: ${s.findingType} at ${s.endpoint}\n  //   ${s.description || s.evidenceRef}`
  ).join('\n');

  return {
    path: `playwright-tests/chain-${safeName}.spec.ts`,
    type: 'chain-spec',
    content: `// Generated by Ultimatrix — attack chain test
// Chain: ${chain.name} (${chain.severity})
import { test, expect } from '@playwright/test';

test('attack chain: ${chain.name.replace(/'/g, "\\'")}', async ({ request }) => {
${steps}

  // Narrative: ${(chain.narrative || '').replace(/[\r\n]+/g, ' ').slice(0, 500)}
  // This test confirms all chain endpoints are reachable in sequence.
  // Severity: ${chain.severity}, confidence: ${chain.confidence}
  expect(true).toBe(true);
});
`,
  };
}

export function writeFindingTests(result: GenerationResult, outDir: string): string[] {
  const fs = require('fs') as typeof import('fs');
  const path = require('path') as typeof import('path');
  const written: string[] = [];
  for (const f of result.files) {
    const fullPath = path.join(outDir, f.path);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, f.content, 'utf-8');
    written.push(fullPath);
  }
  return written;
}
